@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.cleanup.todoc.model.Project#Project(long,String,int)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.cleanup.todoc.model.Project"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_856774308 { 
   	label=cleanup
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1925994771 { 
   	label=todoc
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1161122017 { 
   	label=ProjectDao_Impl
	labeljust=l
	fillcolor=white
	style=filled
   
   ProjectDao_Impl425544231XXXgetProject3327612[
	label="+ getProject()"
	style=filled
	fillcolor=white
	tooltip="ProjectDao_Impl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1519707308 { 
   	label=Project
	labeljust=l
	fillcolor=white
	style=filled
   
   Project2005803681XXXProject1301628282[
	label="+ Project()"
	style=filled
	fillcolor=white
	tooltip="Project

&#10;  Instantiates a new Project.&#10; &#10;  @param idthe unique identifier of the project to set&#10;  @param name the name of the project to set&#10;  @param color the hex (ARGB) code of the color associated to the project to set&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1904702633 { 
   	label=TaskDaoTest
	labeljust=l
	fillcolor=white
	style=filled
   
   TaskDaoTest1258479462XXXinsertAndGetProject0[
	label="+ insertAndGetProject()"
	style=filled
	fillcolor=white
	tooltip="TaskDaoTest

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1976424815 { 
   	label=ProjectDataRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   ProjectDataRepository1295645968XXXgetProject3327612[
	label="+ getProject()"
	style=filled
	fillcolor=white
	tooltip="ProjectDataRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1983094003 { 
   	label=TaskViewModel
	labeljust=l
	fillcolor=white
	style=filled
   
   TaskViewModel592173596XXXinit3327612[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="TaskViewModel

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ProjectDao_Impl425544231XXXgetProject3327612 -> Project2005803681XXXProject1301628282;
ProjectDataRepository1295645968XXXgetProject3327612 -> ProjectDao_Impl425544231XXXgetProject3327612;
TaskDaoTest1258479462XXXinsertAndGetProject0 -> ProjectDao_Impl425544231XXXgetProject3327612;
TaskViewModel592173596XXXinit3327612 -> ProjectDataRepository1295645968XXXgetProject3327612;
    
}
@enduml