@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.cleanup.todoc.model.Project"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_856774308 { 
   	label=cleanup
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1925994771 { 
   	label=todoc
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   MainActivity592173596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adapter: TasksAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   allProjects: Project[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   dialog: AlertDialog [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dialogEditText: EditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dialogSpinner: Spinner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lblNoTasks: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listTasks: RecyclerView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mTaskViewModel: TaskViewModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sortMethod: SortMethod [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tasks: ArrayList&lt;Task&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addTask(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >- configureViewModel()</TD></TR>
<TR><TD ALIGN="LEFT" >- getAllTasks()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateOptionsMenu(menu: Menu): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onDeleteTask(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onOptionsItemSelected(item: MenuItem): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- onPositiveButtonClick(dialogInterface: DialogInterface)</TD></TR>
<TR><TD ALIGN="LEFT" >- populateDialogSpinner()</TD></TR>
<TR><TD ALIGN="LEFT" >- showAddTaskDialog()</TD></TR>
<TR><TD ALIGN="LEFT" >- updateTasks(tasks: List&lt;Task&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MainActivityInstrumentedTest1258479462[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainActivityInstrumentedTest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   rule: ActivityTestRule&lt;MainActivity&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addAndRemoveTask()</TD></TR>
<TR><TD ALIGN="LEFT" >+ sortTasks()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Project2005803681[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Project</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   color: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getProjectById(id: long): Project</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskViewHolder1419102573[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskViewHolder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   deleteTaskListener: DeleteTaskListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imgDelete: AppCompatImageView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imgProject: AppCompatImageView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lblProjectName: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lblTaskName: TextView [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># bind(task: Task)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TaskViewModel592173596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TaskViewModel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   currentProject: LiveData&lt;Project&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   executor: Executor [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   projectDataSource: ProjectDataRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   taskDataSource: TaskDataRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createTask(task: Task)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteTask(taskId: long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getProject(projectId: long): LiveData&lt;Project&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ init(projectId: long)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TasksAdapter592173596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TasksAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   deleteTaskListener: DeleteTaskListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tasks: List&lt;Task&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(taskViewHolder: TaskViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(viewGroup: ViewGroup, viewType: int): TaskViewHolder</TD></TR>
<TR><TD ALIGN="LEFT" ># updateTasks(tasks: List&lt;Task&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
MainActivity592173596 -> Project2005803681[label="allProjects
[0..*]"];
MainActivity592173596 -> TaskViewModel592173596[label="mTaskViewModel
[0..1]"];
MainActivity592173596 -> TasksAdapter592173596[label="adapter
[0..1]"];
MainActivityInstrumentedTest1258479462 -> MainActivity592173596[label="rule
[0..1]"];
TaskViewHolder1419102573 -> MainActivity592173596[label="deleteTaskListener
[0..1]"];
TaskViewModel592173596 -> Project2005803681[label="currentProject
[0..1]"];
TasksAdapter592173596 -> MainActivity592173596[label="deleteTaskListener
[0..1]"];
    
}
@enduml